<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Application\FlutterBuildDoctor.Application.csproj" />
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Infrastructure\FlutterBuildDoctor.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Flutter\FlutterBuildDoctor.Flutter.csproj" />
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Android\FlutterBuildDoctor.Android.csproj" />
  </ItemGroup>
</Project>
