<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Domain\FlutterBuildDoctor.Domain.csproj" />
    <ProjectReference Include="..\..\src\FlutterBuildDoctor.Application\FlutterBuildDoctor.Application.csproj" />
  </ItemGroup>
</Project>
